# Generated by Django 4.2.15 on 2024-09-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_customusermodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='username',
        ),
    ]
