# Generated by Django 4.2.15 on 2024-09-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_remove_customusermodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='name',
            new_name='full_name',
        ),
    ]
