# Generated by Django 4.2.15 on 2024-09-17 03:58

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('base', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.PostPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
