# Generated by Django 4.2.15 on 2024-09-19 03:44

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_videotag_alter_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tagged_items', to='base.video'),
        ),
    ]
