# Generated by Django 4.2.15 on 2024-09-19 03:52

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('base', '0006_videotaggeditem_delete_videotag_alter_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='base.VideoTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
