# Generated by Django 4.2.15 on 2024-09-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_videotag_delete_videotaggeditem_alter_video_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
